# ArrayCreationRoutines

##  Building matrices

### diag,diagflat,trl,trll,trlu,vender

 ### numpy.diag
 Extract a diagonal or construct a diagonal array.

See the more detailed documentation for numpy.diagonal if you use this function to extract a diagonal and wish to write to the resulting array; whether it returns a copy or a view depends on what version of numpy you are using.

In [2]:
import numpy as np

In [8]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# to find only diagonal value
np.diag(x) # output will be: 0,4,8

array([0, 4, 8])

In [10]:
np.diag(x,k=1)

array([1, 5])

In [12]:
np.diag(np.diag(x)) # only diagonal vaule others value is 0

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

### numpy.diagflat(v, k=0)
Create a two-dimensional array with the flattened input as a diagonal.

In [13]:
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### numpy.tri(N, M=None, k=0, dtype=<class 'float'>)
An array with ones at and below the given diagonal and zeros elsewhere.

In [15]:
np.tri(3,4,2)

array([[1., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.tri(8,4,2,dtype=int)

array([[1, 1, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])