# ArrayCreationRoutines 

## From existing data

### array,asarray,asanyarray,ascontinguousarray,asmatrix,copy,frombuffer,fromfile,fromfunction,fromlter,fromstring,loadtext

In [4]:
import numpy as np

In [5]:
# Create an array.

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
# Upcasting
np.array([1,2,3.0])

array([1., 2., 3.])

In [7]:
np.array([3.6,9,10,45,3.6])

array([ 3.6,  9. , 10. , 45. ,  3.6])

In [9]:
#  than one dimension:
a = np.array([[1,2,3,4,5],[2,3,4,5,6]]) # two dimention 2 rows 4 columns
a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [11]:
a.dtype

dtype('int64')

In [14]:
# Minimum dimensions 3:

a = np.array([1,2,3,4],ndmin=3) # show as 3d numpy array sturcture like as [[[]]]
a

array([[[1, 2, 3, 4]]])

In [15]:
a.dtype

dtype('int64')

In [16]:
np.array([1,2,3],ndmin=2)

array([[1, 2, 3]])

In [17]:
# Type provided:
np.array([1,2,3,4],dtype=int)

array([1, 2, 3, 4])

In [18]:
np.array([1,2,3,4],dtype = float)

array([1., 2., 3., 4.])

In [20]:
np.arange(4,dtype = complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j])

In [22]:
# Data-type consisting of more than one element:


np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [23]:
np.array([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

In [25]:
# Return an array copy of the given object.

x = np.array([2,4,5])
y = np.arange(6)
z = np.copy(y)
print('x = ',x,'y = ',y,'copy of y = ',z)

x =  [2 4 5] y =  [0 1 2 3 4 5] copy of y =  [0 1 2 3 4 5]


In [27]:
# modify the return 
x = np.array([4,5,6])
y = np.arange(3)
print(x,y,z) # z value not change

[4 5 6] [0 1 2] [0 1 2 3 4 5]
