# ArrayCreationRoutines 

## Zeroes and Ones

### empty,empty_like,ones,ones_like,zeros,zeros_like,full,full_like,eye,identity

In [1]:
import numpy as np

In [2]:
# create array: empty: Return a new array of given shape and type, without initializing entries.
a = np.empty([2,3]) # 2 rows,3 columns
print(a)

[[2.23499804e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [3]:
a = np.empty([2,5],dtype = np.int8)
print(a)

[[  0   0   0   0   0]
 [  0   0   0 -80 -18]]


In [10]:
# Return a new array with the same shape and type as a given array.
a = np.empty_like([[1,2,3,4],[5,6,7,8]],dtype = np.int8) 
print(a)

[[ 96 -14 -82   2]
 [  0   0   0   0]]


In [11]:
np.empty_like(a)

array([[-128,   66,  -78,    2],
       [   0,    0,    0,    0]], dtype=int8)

In [13]:
ab = np.array([1,2,3,4])
ab

array([1, 2, 3, 4])

In [15]:
np.empty_like(ab)

array([       40611168,               0,              32, 140380069064488])

In [16]:
# Return a new array of given shape and type, filled with ones.

a = np.ones([2,4]) # 2 rows, 4 columns
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
b = np.arange(5,dtype=float)
b

array([0., 1., 2., 3., 4.])

In [29]:
np.ones_like(b)

array([1., 1., 1., 1., 1.])

In [33]:
# Return a new array of given shape and type, filled with fill_value.

np.full([2,3],6) # 6 is given value of rows and columns

array([[6, 6, 6],
       [6, 6, 6]])

In [37]:
np.full_like([2,3],7) # all like return same shape and same type 

array([7, 7])

In [38]:
# Return a new array of given shape and type, filled with zeros.

np.zeros(4)

array([0., 0., 0., 0.])

In [39]:
np.zeros([4,7])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [42]:
np.zeros(a)

TypeError: only integer scalar arrays can be converted to a scalar index

In [43]:
np.zeros_like([4,7])

array([0, 0])

In [44]:
np.zeros(4)

array([0., 0., 0., 0.])

In [51]:
# The identity array is a square array with ones on the main diagonal.

np.identity(5) # diagonal fill up with 1. squre array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
# Return a 2-D array with ones on the diagonal and zeros elsewhere.

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.eye(4,k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
np.eye(8,k=3) # set diagonal position where from it's start

array([[0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#  Assigenment

### 1. create a ndimensional array without initialize value
### 2. create a nd array which all values is 1.
### 3. create a array which all values is 0
### 4. create a array which diagonal number is 1 and all other value is 0
### 5. create a squre array which digonal is 1.
### 6. create a array which all values is 6/7/8